version: '3'

services:
  backend:
    image: professor99/ds-backend:1.0.0
    ports:
      - "4444:4444"
    volumes:
      - ./backend-data:/app/backend/data

  frontend: 
    image: professor99/ds-frontend:1.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-data:/code/frontend/data