export let castArray = {
  SC: [
    { category: "SC", cast_name: "Ager (1)" },
    { category: "SC", cast_name: "Anamook (2)" },
    { category: "SC", cast_name: "Aaremala (3)" },
    { category: "SC", cast_name: "Aarwa Mala (4)" },
    { category: "SC", cast_name: "Bahna, Bahana (5)" },
    { category: "SC", cast_name: "Bakad, Bant (6)" },
    { category: "SC", cast_name: "Balahi, Balaai (7)" },
    { category: "SC", cast_name: "Basor, Burud, Baansor, Baansodi (8)" },
    { category: "SC", cast_name: "Bedajangam, Budagaa Jangam (9)" },
    { category: "SC", cast_name: "Bedar (10)" },
    {
      category: "SC",
      cast_name:
        "Bhaambi, Bhaambhi, Asodi, Chamdiya, Chamaar, Chamaari, Chambhar, Chamgaar, Haralayya, Harali, Khalpa, Machigaar, Mochigaar, Maadar, Maadig, Mochi, Telagu Mochi, Kamati Mochi, Ranigaar, Rohidas, Nona, Ramnami, Rohit, Samgaar, Surajyabanshi, Surajyaramnami (11)",
    },
    {
      category: "SC",
      cast_name:
        "Bhangi, Mehatar, Olagaana, Rukhi, Malkana, Halalkhor, Lalbegi, Balmiki, Karor, Zadgalli (12)",
    },
    { category: "SC", cast_name: "Bindala (13)" },
    { category: "SC", cast_name: "Byagara (14)" },
    { category: "SC", cast_name: "Chalwaadi, Channaya (15)" },
    {
      category: "SC",
      cast_name: "Chennadaasar, Holaya Daasar, Holeya Dasaari (16)",
    },
    { category: "SC", cast_name: "Dakkal, Dokkalwar (17)" },
    { category: "SC", cast_name: "Dhor, Kakkayya, Kankayya, Dohor (18)" },
    { category: "SC", cast_name: "Dom, Dumar (19)" },
    { category: "SC", cast_name: "Yallamwar, Yellamalvandalu (20)" },
    { category: "SC", cast_name: "Ganda, Gandi (21)" },
    { category: "SC", cast_name: "Garoda, Gaaro (22)" },
    { category: "SC", cast_name: "Ghassi, Ghassiya (23)" },
    { category: "SC", cast_name: "Hallir (24)" },
    { category: "SC", cast_name: "Halsaar, Hasalaar, Hulsawar (25)" },
    { category: "SC", cast_name: "Holar, Vhalar (26)" },
    { category: "SC", cast_name: "Holaya, Holer, Holeyaa, Holiyaa (27)" },
    {
      category: "SC",
      cast_name:
        "Kaikadi Akola, Amaravati, Bhandara, Buldhana, Nagpur, Vardha and Yavatmal Districts. And Chadrapur dist except Rajura Taluka. (28)",
    },
    { category: "SC", cast_name: "Katiya, Pathariya (29)" },
    { category: "SC", cast_name: "Khangar, Kanera, Mirdha (30)" },
    { category: "SC", cast_name: "Khatik, Chikwa, Chikvi (31)" },
    { category: "SC", cast_name: "Kolupool-Wandalu (32)" },
    { category: "SC", cast_name: "Kori (33)" },
    { category: "SC", cast_name: "Lingader (34)" },
    { category: "SC", cast_name: "Maadagi (35)" },
    { category: "SC", cast_name: "Maadiga (36)" },
    {
      category: "SC",
      cast_name: "Mahar, Meharaa, Taral, Dhegu-Megu (37)",
    },
    {
      category: "SC",
      cast_name: "Maahayaavanshi, Dhed, Vankar, Maru-Vankar (38)",
    },
    { category: "SC", cast_name: "Mala (39)" },
    { category: "SC", cast_name: "Mala Daasari (40)" },
    { category: "SC", cast_name: "Mala Hannai (41)" },
    { category: "SC", cast_name: "Mala Jangam (42)" },
    { category: "SC", cast_name: "Mala Masti (43)" },
    { category: "SC", cast_name: "Mala Saale, Netkanee (44)" },
    { category: "SC", cast_name: "Mala Sanyasi (45)" },
    {
      category: "SC",
      cast_name:
        "Mang, Matang, Minimaadig, Dakhani-Mang, MangMhashi, Madaari, Gaarudi, Radhemang (46)",
    },
    { category: "SC", cast_name: "Mang-Garodi, Mang-Garudi (47)" },
    { category: "SC", cast_name: "Manne (48)" },
    { category: "SC", cast_name: "Masti (49)" },
    { category: "SC", cast_name: "Menghwal, Menghwar (50)" },
    { category: "SC", cast_name: "Mitha, Ayalwar (51)" },
    { category: "SC", cast_name: "Mukri (52)" },
    { category: "SC", cast_name: "Nadiya, Haadi (53)" },
    { category: "SC", cast_name: "Paasi (54)" },
    { category: "SC", cast_name: "Saansi (55)" },
    { category: "SC", cast_name: "Shenwa, Chenwa, Sedamaa, Ravat (56)" },
    { category: "SC", cast_name: "Sindhollu, Chindollu (57)" },
    { category: "SC", cast_name: "Tirgaar, Tirbanda (58)" },
    { category: "SC", cast_name: "Toori (59)" },
  ],

  ST: [
    { category: "ST", cast_name: "Andh (1)" },
    { category: "ST", cast_name: "Baiga (2)" },
    { category: "ST", cast_name: "Barda (3)" },
    { category: "ST", cast_name: "Bavacha, Bamcha (4)" },
    { category: "ST", cast_name: "Bhaina (5)" },
    {
      category: "ST",
      cast_name: "Bharia Bhumia, Bhuinhar Bhumia, Pando (6)",
    },
    { category: "ST", cast_name: "Bhattra (7)" },
    {
      category: "ST",
      cast_name:
        "Bhil, Bhil garasia, Dholi, Bhil, Dangri Bhil, Dungri, Garasia, Mewsi Bhil, Rawal Bhil, Tadvi Bhil, Bhagalia, Bhilala Pawra, Vasava, Vasave (8)",
    },
    { category: "ST", cast_name: "Bhunjia (9)" },
    { category: "ST", cast_name: "Binjhwar (10)" },
    { category: "ST", cast_name: "Birhul, Birhor (11)" },
    {
      category: "ST",
      cast_name:
        "Chodhara (excluding Akola, Amravati, Bhandara, Buldana, Chandrapur, Nagpur, Wardha, Yavatmal, Aurangabad, Bhir, Nanded, Osmanabad and Parbhani districts) (12)",
    },
    { category: "ST", cast_name: "Dhanka, Tadvi, Tetaria, Valvi (13)" },
    { category: "ST", cast_name: "Dhanwar (14)" },
    { category: "ST", cast_name: "Dhodia (15)" },
    { category: "ST", cast_name: "Dubla Talavia, Halpati (16)" },
    {
      category: "ST",
      cast_name: "Gamit, Gamta, Gavit, Mavchi, Padvi (17)",
    },
    {
      category: "ST",
      cast_name:
        "Gond, Rajgond, Arakh, Arrakh, Agaria, Asur, Bedi Maria, Bada Maria, Bhatola, Bhimma, Bhuta, Koilabhuta, Koilabhuti, Bhar, Bisonhorn Maria, Chota Maria, Dandami Maria, Dhuru, Dhurwa, Dhoba, Dhulia, Dorla, Kaiki, Gatta, Gatti, Gaita, Gond Gowari, Hill Maria, Kandara Kalanga, Khatola, Koitar, Koya, Khirwar, Khirwara, Kucha Maria, Kuchaki Maria, Media, Maria, Mana, Meannewar, Moghya, Mogia Moghya, Mudia, Muria, Nagarchi, Naikpod, Nagwanshi, Ojha, Raj Sonjhari Jhareka, Thatia, Thotya, Wade Maria, Vade Maria. (18)",
    },
    { category: "ST", cast_name: "Halba, Balbi (19)" },
    { category: "ST", cast_name: "Kamar (20)" },
    {
      category: "ST",
      cast_name:
        "Kathodi, Katkari, Dhor Kathodi, Dhor Kathkari, Son Kathodi, Son Katkari (21)",
    },
    {
      category: "ST",
      cast_name: "Kawar, Kanwar, Kaur, Cherwa, Rathia, Tanwar, Chattri (22)",
    },
    { category: "ST", cast_name: "Khairwar (23)" },
    { category: "ST", cast_name: "Kharia (24)" },
    { category: "ST", cast_name: "Kokna, Kokni, Kukna (25)" },
    { category: "ST", cast_name: "Kol (26)" },
    { category: "ST", cast_name: "Kolam, Mannervarlu (27)" },
    {
      category: "ST",
      cast_name: "Koli dhor, Tokre Koli, Kolcha, Kolgha (28)",
    },
    { category: "ST", cast_name: "Koli Mahadev, Dongar Koli (29)" },
    { category: "ST", cast_name: "Koli Malhar (30)" },
    { category: "ST", cast_name: "Kondh, Khond, Kandh (31)" },
    {
      category: "ST",
      cast_name: "Korku, Bopchi, Mouasi, Nihal, Nahul, Bondhi, Bondeya (32)",
    },
    { category: "ST", cast_name: "Koya, Bhine Koya, Rajkoya (33)" },
    { category: "ST", cast_name: "Nagesia, Nagasia (34)" },
    {
      category: "ST",
      cast_name:
        "Naikda, Nayaka, Cholivala Nayaka, Kapadia Nayaka,, Mota Nayaka, Nana Nayaka (35)",
    },
    { category: "ST", cast_name: "Oraon, Dhangad (36)" },
    { category: "ST", cast_name: "Pardhan, Pathari, Saroti (37)" },
    {
      category: "ST",
      cast_name:
        "Pardhi, Advichincher, Phans Pardhi, Phanse Pardhi, Langoli Pardhi, Behelia, Behellia, Chita Pardhi, Shikari, Takankar, Takia (38)",
    },
    { category: "ST", cast_name: "Parja (39)" },
    { category: "ST", cast_name: "Patelia (40)" },
    { category: "ST", cast_name: "Pomla (41)" },
    { category: "ST", cast_name: "Rathwa (42)" },
    { category: "ST", cast_name: "Sawar, Sawara (43)" },
    {
      category: "ST",
      cast_name: "Thakur, Thakar, Ka Thakar, Ma Thakur, Ma Thakar (44)",
    },
    {
      category: "ST",
      cast_name:
        "Thoti (in Aurangabad, Bhir Nanded, Osmanabed and Parbhani districts and Rajura tahsil of Chandrapur district) (45)",
    },
    { category: "ST", cast_name: "Varli (46)" },
    { category: "ST", cast_name: "Vitolia, Kotwalia, Barodia (47)" },
  ],
  OPEN: [{}],
  SBC: [
    { category: "SBC", cast_name: "(1)(1)Gawari" },
    { category: "SBC", cast_name: "(1)(1)Gowari" },
    { category: "SBC", cast_name: "(3)(1)Koshti" },
    { category: "SBC", cast_name: "(3)(10)DeWang" },
    { category: "SBC", cast_name: "(3)(11)Kachi Bandhhe" },
    { category: "SBC", cast_name: "(3)(12)Patvis" },
    { category: "SBC", cast_name: "(3)(13)Satsale" },
    { category: "SBC", cast_name: "(3)(14)Sade" },
    { category: "SBC", cast_name: "(3)(15)JainKoshti" },
    { category: "SBC", cast_name: "(3)(16)Lingayat Dewang" },
    { category: "SBC", cast_name: "(3)(16)Lingayat Sali" },
    { category: "SBC", cast_name: "(3)(16)Lingayat Koshti" },
    { category: "SBC", cast_name: "(3)(2)Halba Koshti" },
    { category: "SBC", cast_name: "(3)(4)Sali" },
    { category: "SBC", cast_name: "(3)(4)Swakul Sali" },
    { category: "SBC", cast_name: "(3)(5)Lad Koshti" },
    { category: "SBC", cast_name: "(3)(6)Gaddhewal Koshti" },
    { category: "SBC", cast_name: "(3)(9)Chanewar" },
    { category: "SBC", cast_name: "(3)(9)Channewar" },
    { category: "SBC", cast_name: "(3)(9)Chenewar" },
    { category: "SBC", cast_name: "(3)(9)Padmashali" },
    { category: "SBC", cast_name: "(3)(9)Salewar" },
    { category: "SBC", cast_name: "(4)(1)Koli" },
    { category: "SBC", cast_name: "(4)(10)Mangela" },
    { category: "SBC", cast_name: "(4)(11)Sonkoli" },
    { category: "SBC", cast_name: "(4)(12)Vaiti" },
    { category: "SBC", cast_name: "(4)(13)Kharva" },
    { category: "SBC", cast_name: "(4)(13)Kharvi" },
    { category: "SBC", cast_name: "(4)(14)Koli (Non included in ST)" },
    { category: "SBC", cast_name: "(4)(15)Machhi" },
    { category: "SBC", cast_name: "(4)(15)Machhi Mitna" },
    { category: "SBC", cast_name: "(4)(2)Machhimar Koli" },
    { category: "SBC", cast_name: "(4)(3)Ahir Koli" },
    { category: "SBC", cast_name: "(4)(4)Khandeshi Koli" },
    { category: "SBC", cast_name: "(4)(5)Pankoli" },
    { category: "SBC", cast_name: "(4)(6)Christian Koli" },
    { category: "SBC", cast_name: "(4)(7)Chumbale Koli" },
    { category: "SBC", cast_name: "(4)(8)Panbhare Koli" },
    { category: "SBC", cast_name: "(4)(9)Koli Suryawanshi" },
    { category: "SBC", cast_name: "(5)(1)Munnerwar" },
    { category: "SBC", cast_name: "(5)(10)Telugu Phulmali" },
    { category: "SBC", cast_name: "(5)(2)Munnurwar" },
    { category: "SBC", cast_name: "(5)(3)Munnur" },
    { category: "SBC", cast_name: "(5)(4)Telugu Munnur" },
    { category: "SBC", cast_name: "(5)(5)Munnurvar Telugu" },
    { category: "SBC", cast_name: "(5)(8)Telugu Kapewar" },
    { category: "SBC", cast_name: "(5)(9)Munnarwad" },
    { category: "SBC", cast_name: "(6)Gabit" },
    { category: "SBC", cast_name: "(7)Muslim Religious Bhangi" },
    { category: "SBC", cast_name: "(7)Muslim Religious Halalkhor" },
    { category: "SBC", cast_name: "(7)Muslim Religious Khakrob" },
    { category: "SBC", cast_name: "(7)Muslim Religious Lalbeg" },
    { category: "SBC", cast_name: "(7)Muslim Religious Mehatkar" },
  ],
  VJNT: [
    { category: "VJNT", cast_name: "Gosavi (1)" },
    { category: "VJNT", cast_name: "Beldar (2)" },
    { category: "VJNT", cast_name: "Bharaadi (3)" },
    { category: "VJNT", cast_name: "Bhute (Bhope) (4)" },
    { category: "VJNT", cast_name: "Chitrakathi (6)" },
    {
      category: "VJNT",
      cast_name: "Garudi (Saapgarudi, incl Muslim) (7)",
    },
    { category: "VJNT", cast_name: "Lohar (8)" },
    {
      category: "VJNT",
      cast_name: "Golla (Gollewar, Goler, Golkar) (9)",
    },
    { category: "VJNT", cast_name: "Gondhali (10)" },
    { category: "VJNT", cast_name: "Gopal (11)" },
    { category: "VJNT", cast_name: "Helave (Hilav) (12)" },
    { category: "VJNT", cast_name: "Joshi (13)" },
    { category: "VJNT", cast_name: "Kashi Kapdi (14)" },
    { category: "VJNT", cast_name: "Kolhati (Dombari) (15)" },
    { category: "VJNT", cast_name: "Mairal (16)" },
    { category: "VJNT", cast_name: "Masanjogi (17)" },
    { category: "VJNT", cast_name: "Nandiwale (Tirmal) (18)" },
    { category: "VJNT", cast_name: "Pangul (19)" },
    { category: "VJNT", cast_name: "Rawal (Raul or Ravalyogi) (20)" },
    {
      category: "VJNT",
      cast_name:
        "Sikkalgar (Katari, Sekkalgar (Muslim), Sikh Shikaligaar, Sikh Shikalikar, Shikalgar, Shikaligar etc.) (21)",
    },
    { category: "VJNT", cast_name: "Thakar (22)" },
    { category: "VJNT", cast_name: "Vaidu (23)" },
    { category: "VJNT", cast_name: "Vasudeo (24)" },
    { category: "VJNT", cast_name: "Bhoi (25)" },
    { category: "VJNT", cast_name: "Bahurupi (26)" },
    { category: "VJNT", cast_name: "Thhelari (27)" },
    { category: "VJNT", cast_name: "Otaari (28)" },
    { category: "VJNT", cast_name: "NT C: Dhangar (29)" },
    { category: "VJNT", cast_name: "NT D: Vanjari (30)" },
    {
      category: "VJNT",
      cast_name: "Mari aaiwale, Kadak Laxmiwale, Margammawale (31)",
    },
    { category: "VJNT", cast_name: "Gihara/Gahara (32)" },
    { category: "VJNT", cast_name: "Gusai/Gosai (33)" },
    {
      category: "VJNT",
      cast_name: "Muslim Madari, Garudi, Sanpwale & Jadugar (34)",
    },
    { category: "VJNT", cast_name: "Indian Irani (35)" },
    {
      category: "VJNT",
      cast_name: "Gavali, Muslim Gavali (Gawalan *, Gwalvansh *) (36)",
    },
    {
      category: "VJNT",
      cast_name: "Darveshi, Waghwale – Shah (Muslim), Aswalwale (37)",
    },
  ],
};
