export let obcArray = [
  { category: "OBC", cast_name: "Alitkar (1)" },
  { category: "OBC", cast_name: "Bagdi (2)" },
  { category: "OBC", cast_name: "Badia (4)" },
  { category: "OBC", cast_name: "Bajania (5)" },
  { category: "OBC", cast_name: "Bajigar (6)" },
  { category: "OBC", cast_name: "Buttal (7)" },
  { category: "OBC", cast_name: "Bhand, Chappar Bhand (8)" },
  { category: "OBC", cast_name: "Bavaiya or Targal (9)" },
  { category: "OBC", cast_name: "Bhavin (10)" },
  { category: "OBC", cast_name: "Bhisti or Pakhali, Sakka (11)" },
  { category: "OBC", cast_name: "Bari or Barai (13)" },
  { category: "OBC", cast_name: "Beriya (14)" },
  { category: "OBC", cast_name: "Besdeva (15)" },
  {
    category: "OBC",
    cast_name:
      "Bhadbhunja, Bhujaya, Bhunjva, Bhurji, Bharadbhunja, Bhuranji, Bhunj (16)",
  },
  { category: "OBC", cast_name: "Bhanta (17)" },
  { category: "OBC", cast_name: "Bhat Bhaat (18)" },
  { category: "OBC", cast_name: "Chamatha (19)" },
  { category: "OBC", cast_name: "Chandalgada (20)" },
  { category: "OBC", cast_name: "Charan or Gadhavi (21)" },
  { category: "OBC", cast_name: "Charodi (22)" },
  { category: "OBC", cast_name: "Chippa, Chhipa (23)" },
  { category: "OBC", cast_name: "Das or Dangadidas (24)" },
  { category: "OBC", cast_name: "Davgar (25)" },
  { category: "OBC", cast_name: "Depala (26)" },
  { category: "OBC", cast_name: "Devali (27)" },
  { category: "OBC", cast_name: "Devdig, Devadiga (28)" },
  { category: "OBC", cast_name: "Dholi, Hashmi/ Dafali (30)" },
  { category: "OBC", cast_name: "Gandharap (35)" },
  { category: "OBC", cast_name: "Gujrath Bori (36)" },
  { category: "OBC", cast_name: "Gadhavi (39)" },
  { category: "OBC", cast_name: "Bandi (130)" },
  { category: "OBC", cast_name: "Rachbandhiya (131)" },
  { category: "OBC", cast_name: "Rangari (132)" },
  { category: "OBC", cast_name: "Ragrez (133)" },
  { category: "OBC", cast_name: "Raot, Ravat, Rautiya (134)" },
  { category: "OBC", cast_name: "Rangrez (Bhavsar, Rangari) (135)" },
  { category: "OBC", cast_name: "Sanjogi (140)" },
  { category: "OBC", cast_name: "Saraaniya (141)" },
  { category: "OBC", cast_name: "Suppaling (145)" },
  { category: "OBC", cast_name: "Sutharia (In Sindh) (146)" },
  { category: "OBC", cast_name: "Sahis, Saes, Shis (147)" },
  { category: "OBC", cast_name: "Sapera (148)" },
  { category: "OBC", cast_name: "Shilavat (149)" },
  { category: "OBC", cast_name: "Singiwala (150)" },
  {
    category: "OBC",
    cast_name:
      "Shimpi, Idrisi/Darji, Sai Sutar, Jain Shimpi, Shravak Shimpi, Shetwal, Shetval, Saitwal, Saitval, Meru Shimpi / Meru Kshatriya Shimpi (153)",
  },
  { category: "OBC", cast_name: "Sonar (154)" },
  { category: "OBC", cast_name: "Tandel (155)" },
  { category: "OBC", cast_name: "Targala (157)" },
  { category: "OBC", cast_name: "Thetwar (158)" },
  { category: "OBC", cast_name: "Thoria (159)" },
  { category: "OBC", cast_name: "Tambat, Twashta Kasar, Kasar (160)" },
  { category: "OBC", cast_name: "Thogati (161)" },
  { category: "OBC", cast_name: "Wadi (162)" },
  { category: "OBC", cast_name: "Wansphod, Hindu Dharkar (164)" },
  { category: "OBC", cast_name: "Chintala (234)" },
  { category: "OBC", cast_name: "Dakaleru (235)" },
  { category: "OBC", cast_name: "Darji (236)" },
  { category: "OBC", cast_name: "Kurba, Kurubar (238)" },
  {
    category: "OBC",
    cast_name: "Harkantra, Mangeli, Mangele, Page, Sanduri (239)",
  },
  { category: "OBC", cast_name: "Wats, Bhadwal, Rajak (240)" },
  { category: "OBC", cast_name: "Dommara (241)" },
  { category: "OBC", cast_name: "Gaadaaba or Godaba (242)" },
  { category: "OBC", cast_name: "Gangani (243)" },
  { category: "OBC", cast_name: "Garodi (244)" },
  { category: "OBC", cast_name: "Goller (245)" },
  { category: "OBC", cast_name: "Godala (246)" },
  { category: "OBC", cast_name: "Habura (247)" },
  { category: "OBC", cast_name: "Harani (248)" },
  { category: "OBC", cast_name: "Hil- Redidas (249)" },
  { category: "OBC", cast_name: "Deveri (250)" },
  { category: "OBC", cast_name: "Winkar, Wanya, Bankar (251)" },
  { category: "OBC", cast_name: "Kachiya (252)" },
  { category: "OBC", cast_name: "Korach, Padlor (253)" },
  {
    category: "OBC",
    cast_name:
      "Kalal, Kalar, Lad, Ladwak, Goud Kalal, Shivhare - excluding Lad Barahman (comment added in June 2008) (254)",
  },
  { category: "OBC", cast_name: "Kandel (255)" },
  { category: "OBC", cast_name: "Kasera (256)" },
  { category: "OBC", cast_name: "Kasai, Kasab, Kureshi (257)" },
  { category: "OBC", cast_name: "Katipamula (258)" },
  { category: "OBC", cast_name: "Kirar (259)" },
  { category: "OBC", cast_name: "Christian Koli (260)" },
  { category: "OBC", cast_name: "Korachar or Korave (261)" },
  { category: "OBC", cast_name: "Kodaku with Korava (262)" },
  { category: "OBC", cast_name: "Komakapu (263)" },
  { category: "OBC", cast_name: "Kondu (264)" },
  { category: "OBC", cast_name: "Lakhari (265)" },
  {
    category: "OBC",
    cast_name: "Lohar-Gada, Dodi, Panchal, Khatawali (266)",
  },
  { category: "OBC", cast_name: "Chunari (267)" },
  { category: "OBC", cast_name: "Mahil (269)" },
  { category: "OBC", cast_name: "Maidasi (270)" },
  { category: "OBC", cast_name: "Mazwar (271)" },
  { category: "OBC", cast_name: "Matiyara, Matihara (272)" },
  { category: "OBC", cast_name: "Mankar khalu (273)" },
  { category: "OBC", cast_name: "Mondiwar, Mondiwara (274)" },
  { category: "OBC", cast_name: "Munda (275)" },
  {
    category: "OBC",
    cast_name: "Hajam, Kalseru, Navliga, Kanshi, Nabhik, Nai, Waland (276)",
  },
  { category: "OBC", cast_name: "Pachbhotala, Pachbotala (277)" },
  { category: "OBC", cast_name: "Padampari (278)" },
  { category: "OBC", cast_name: "Bhisti (279)" },
  { category: "OBC", cast_name: "Pamula (280)" },
  { category: "OBC", cast_name: "Panchama (281)" },
  { category: "OBC", cast_name: "Panda (282)" },
  { category: "OBC", cast_name: "Phar (283)" },
  { category: "OBC", cast_name: "Pinjari (284)" },
  { category: "OBC", cast_name: "Purwali (285)" },
  { category: "OBC", cast_name: "Rachbhoya (286)" },
  { category: "OBC", cast_name: "Rautiya (287)" },
  { category: "OBC", cast_name: "Sangari (288)" },
  { category: "OBC", cast_name: "Santal (289)" },
  { category: "OBC", cast_name: "Saunta or Sonta (290)" },
  { category: "OBC", cast_name: "Savteli (291)" },
  { category: "OBC", cast_name: "Sare (292)" },
  { category: "OBC", cast_name: "Bhavgar, Shiv shimpi, Namdev (293)" },
  { category: "OBC", cast_name: "Shingdav or Shingadya (294)" },
  { category: "OBC", cast_name: "Sindhur (295)" },
  { category: "OBC", cast_name: "Sore (296)" },
  { category: "OBC", cast_name: "Sunna (297)" },
  { category: "OBC", cast_name: "Sunnai (298)" },
  { category: "OBC", cast_name: "Bhadai (299)" },
  { category: "OBC", cast_name: "Ganninga, ganchi (300)" },
  { category: "OBC", cast_name: "Thotewadu (301)" },
  { category: "OBC", cast_name: "Timali (302)" },
  { category: "OBC", cast_name: "Walwai (303)" },
  {
    category: "OBC",
    cast_name: "Wadder (Kalawader or Pathroad) (304)",
  },
  { category: "OBC", cast_name: "Wanadi (305)" },
  { category: "OBC", cast_name: "Yenadiwadas (306)" },
  {
    category: "OBC",
    cast_name: "Yergolawad or Thella pamalwadas (307)",
  },
  { category: "OBC", cast_name: "Odewar (308)" },
  {
    category: "OBC",
    cast_name: "Manyar (Bangalwala), Maniyar, Maneri (309)",
  },
  { category: "OBC", cast_name: "Jaatgaar (310)" },
  { category: "OBC", cast_name: "Karadi (311)" },
  { category: "OBC", cast_name: "Kunkuw (312)" },
  {
    category: "OBC",
    cast_name: "Wadhai (deleted * in June 2008), Deleted, Khat-wadhai (313)",
  },
  { category: "OBC", cast_name: "Kohali (315)" },
  { category: "OBC", cast_name: "Khatik, Kureshi Khatik, Kasai (316)" },
  { category: "OBC", cast_name: "Daangari (317)" },
  { category: "OBC", cast_name: "Wedu (Waghari) (318)" },
  { category: "OBC", cast_name: "Dhawad (319)" },
  { category: "OBC", cast_name: "Nirhali (Nirali) (320)" },
  { category: "OBC", cast_name: "Chitrakathi - Hardas (321)" },
  { category: "OBC", cast_name: "Besta, Besti. Bestallu (322)" },
  { category: "OBC", cast_name: "Parivar (323)" },
  { category: "OBC", cast_name: "Sawakalar (324)" },
  { category: "OBC", cast_name: "Hanbar (325)" },
  {
    category: "OBC",
    cast_name:
      "Dode Gujar, Gujar, Leve Gujar, Reve Gujar, Reva Gujar, Suryavanshi Gujar, Badgujar similar castes- Londhari */Pendhari * (326)",
  },
  { category: "OBC", cast_name: "Pahad / Pahadi (327)" },
  { category: "OBC", cast_name: "Gadriya (328)" },
  { category: "OBC", cast_name: "Machhimar (Daldi) (329)" },
  { category: "OBC", cast_name: "Bhaldar (330)" },
  { category: "OBC", cast_name: "Alkari (331)" },
  { category: "OBC", cast_name: "Pendhari (332)" },
  { category: "OBC", cast_name: "Yalam / Yelam / Yallam (333)" },
  { category: "OBC", cast_name: "Mahat / Mahut, Mahawat (334)" },
  { category: "OBC", cast_name: "Fakir (335)" },
  { category: "OBC", cast_name: "Loth, Lotha, Lothi (336)" },
  { category: "OBC", cast_name: "Nalband (337)" },
  {
    category: "OBC",
    cast_name: "Kulekadgi, Kullekadgi, Kulakadgi, Kullakadgi (338)",
  },
  { category: "OBC", cast_name: "Mujavar (339)" },
  { category: "OBC", cast_name: "Mulana, Mulani, Mulane (340)" },
  {
    category: "OBC",
    cast_name: "East Indian, East Indian Christian, East Indian Katholic (341)",
  },
  { category: "OBC", cast_name: "Lad Shakhiya Wani * (343)" },
  { category: "OBC", cast_name: "Muslim - Kakar * (344)" },
  { category: "OBC", cast_name: "Dorik * (345)" },
  { category: "OBC", cast_name: "Patwa * (346)" },
];
